name: Release Drafter

on:
  push:
    branches:
      - latest

jobs:
  release-drafter:
    uses: donavanbecker/.github/.github/workflows/release-drafter.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}